### ISSUE TITLE
Spec explanation unclear on what it is expecting

### ISSUE THREAD

**Issue by sammarcus** [learn-co-students/intro-to-simple-array-manipulations-000#2]
A student had mentioned Line 122 in the spec was confusing the way the comment was worded, perhaps reword for clarity?

https://github.com/learn-co-students/intro-to-simple-array-manipulations-000/blob/c08c6d87db65181f9705354606947aef90ed971c/spec/intro_to_simple_array_manipulations_spec.rb#L122

**Comment by markedwardmurray** [comment]
looks like this has been rewritten
